export enum MsgEvent{

    OP_TOUCH_MOVE = "OP_TOUCH_MOVE",
    OP_TOUCH_SCALE = "OP_TOUCH_SCALE",
    OP_TOUCH_ROTA = "OP_TOUCH_ROTA",
    OP_RESET_CLICK_POINT = "OP_RESET_CLICK_POINT",
    OP_TOUCH_MOVE_MAP = "OP_TOUCH_MOVE_MAP",
}